### ISSUE TITLE
Insecured connection triggers "x509: certificate signed by unknown authority" Error

### ISSUE THREAD

**Issue by clementlefevre** [exasol/exasol-driver-go#23] opened 2021-07-10 18:56 UTC
First of all, thanks for this cool package !

When using the insecure option, i still do get an **"x509: certificate signed by unknown authority"** when querying the DB :
```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/exasol/exasol-driver-go"
)

func main() {
	log.Printf("Drivers=%#v\n", sql.Drivers())
	db, err := sql.Open("exasol", "exa:<host>:<port>;user=<user>;password=<password>;insecure=1")
	if err != nil {
		fmt.Println(err)
	}
	defer db.Close()

	err = db.Ping()
	if err != nil {
		fmt.Println(err)
	}

}

```
returns :

```bash
$ go run exasol_sql.go
2021/07/10 20:51:13 Drivers=[]string{"exasol"}
x509: certificate signed by unknown authority
```
When using the [go-exasol-client](github.com/grantstreetgroup/go-exasol-client) i can set the same config with :
```go
conf := exasol.ConnConf{
		Host:      <host>",
		Port:      <port>,
		Username:  <user>,
		Password:  <password>,
		TLSConfig: &tls.Config{InsecureSkipVerify: true},
	}
```
which works seamlessly. But i would like to take advantage of the binding with the "database/sql" package.
If anyone could give any hint, i would be very thankful ! 

Cheers, 
Clement.

**Comment by AnastasiiaSergienko** [comment] 2021-07-12 08:54
Hello @clementlefevre 
We have checked the code, and we have the InsecureSkipVerify configuration implemented (https://github.com/exasol/exasol-driver-go/blob/main/websocket.go#L80). So it would work in theory. 
Could you please confirm that you're using the latest code from this repository as the feature was implemented recently?

Also, could you please try using a connection string builder and see if the problem is still there?
Example:
db, _ := sql.Open("exasol", exasol.NewConfig("sys", "<your password>").Insecure(true).Port(8563).String())

**Comment by clementlefevre** [comment] 2021-07-12 10:18
Dear Anastasiia, 

First of all, thanks for your reactivity !
Following your advices, i did like this :

```bash
$ go get -u all
```
the exasol-driver-go package seems to be up-to-date.


then i modified the script  using the Connection string builder :
```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	"github.com/exasol/exasol-driver-go"
)

func main() {
	log.Printf("Drivers=%#v\n", sql.Drivers())
	db, err := sql.Open("exasol", exasol.NewConfig("user", "pwd").Port(port).Insecure(true).Host("host_url").String())
	defer db.Close()
	if err != nil {
		fmt.Println(err)
	}
	err = db.Ping()
	if err != nil {
		fmt.Println(err)
	}
}
```

resulting in :
```bash
$ go run exasol_sql.go
2021/07/12 12:03:38 Drivers=[]string{"exasol"}
x509: certificate signed by unknown authority
```

which is the same output as in my initial trial.
FYI, i am behind a **VPN & a Company proxy.**

Again, i really appreciate your support !

Cheers,
Clement.

**Comment by AnastasiiaSergienko** [comment] 2021-07-12 12:13
Thanks for the information @clementlefevre 

We are going to investigate the issue and try to reproduce the error.

Meanwhile, you can try setting the encryption=0 property, which will change the protocol from WSS to insecure WS. And if I understood this correctly, the third-party library does exactly this when you set the insecure option.

Best Regards,
Anastasiia Sergienko

**Comment by clementlefevre** [comment] 2021-07-12 13:12
__Addendum__ :  the Exasol DB i am working with : 
```sql
select param_value from exa_metadata where param_name = 'databaseProductVersion';
``` 
returns **7.0.10**

**Comment by AnastasiiaSergienko** [comment] 2021-07-12 14:14
@clementlefevre 

Some additional questions:
- What is the environment setup? Where is the Exasol instance running and where are you trying to access it from?
- Is Exasol a docker container, a cluster, a single Node instance? 
- Does it work if you set "encryption=0" property?

P.S. Please be aware that we have just renamed "insecure" parameter to "secure", so it's a reversed valuenow to disable TLS/SSL verification (secure=0).

Thank you in advance for supporting our investigation!

**Comment by clementlefevre** [comment] 2021-07-13 07:05
Hallo Anastasiaa,

to answer your questions :

- **Where is the Exasol instance running and where are you trying to access it from?**
 Multiple Exasol nodes are running on the same AWS instance, they are **not** containerized.
On the client side i am with a Windows 10 setup and a
 ```bash
$ go version
go version go1.16.3 windows/amd64
``` 

- **Does it work if you set "encryption=0" property?**
i did update the package following your previous comment :
```bash
$  go get -u all
go: downloading github.com/exasol/exasol-driver-go v0.0.0-20210712135658-11b25715051c
go get: upgraded github.com/exasol/exasol-driver-go v0.0.0-20210702101400-1895ed008131 => v0.0.0-20210712135658-11b25715051c
```
Then tried the 4 possibles combinations of *secure* & *encryption* :

```go
package main

import (
	"database/sql"
	"log"
	"os"

	"github.com/exasol/exasol-driver-go"
)

func testDBConn(secure bool, encryption bool) {
	log.Println("-------------- new Test Config----------")
	log.Printf("secure:%v - encryption:%v", secure, encryption)
	db, err := sql.Open("exasol", exasol.NewConfig(<USER>,<PWD>).Port(<PORT>).Secure(secure).Encryption(encryption).Host(<HOST>).String())
	defer db.Close()
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Connection to DB created. trying to Ping DB...")
	err = db.Ping()
	if err != nil {
		log.Println(err)
	}

}

func main() {
	testDBConn(true, true)
	testDBConn(true, false)
	testDBConn(false, true)
	testDBConn(false, false)

}

```

resulting in :
```bash
$ go run exasol_sql.go
2021/07/13 08:58:02 -------------- new Test Config----------
2021/07/13 08:58:02 secure:true - encryption:true
2021/07/13 08:58:02 Connection to DB created. trying to Ping DB...
2021/07/13 08:58:02 x509: certificate signed by unknown authority
2021/07/13 08:58:02 -------------- new Test Config----------
2021/07/13 08:58:02 secure:true - encryption:false
2021/07/13 08:58:02 Connection to DB created. trying to Ping DB...
2021/07/13 08:58:02 x509: certificate signed by unknown authority
2021/07/13 08:58:02 -------------- new Test Config----------
2021/07/13 08:58:02 secure:false - encryption:true
2021/07/13 08:58:02 Connection to DB created. trying to Ping DB...
2021/07/13 08:58:05 [08004] Connection exception - authentication failed.
2021/07/13 08:58:05 -------------- new Test Config----------
2021/07/13 08:58:05 secure:false - encryption:false
2021/07/13 08:58:05 Connection to DB created. trying to Ping DB...
2021/07/13 08:58:08 [08004] Connection exception - authentication failed.
```

hoping this can help you,

Cheers,

Clement.

**Comment by AnastasiiaSergienko** [comment] 2021-07-13 09:20
Hello @clementlefevre 

Thanks for your reply. The test you did is very helpful. 

According to the result you provided, disabling TLS with secure:false works as expected (you get x509 error only when it's enabled). When it is disabled (two last results), you have a different error: [08004] Connection exception - authentication failed.
This error comes directly from the database and it means that a username or a password is incorrect. So if you provide the correct credentials, your connection should work.

Please, let me know if I understood your problem incorrectly and you need additional assistance. 

Best Regards,
Anastasiia Sergienko

**Comment by clementlefevre** [comment] 2021-07-13 12:02
Dear Anastasiaa,

Thaanks again for those explanation. 
Before we close this issue, i am wondering whether the problem could be related to the dsn parsing method : my Exasol Password contains the  special character **!** (exclamation mark) , could it be the root cause  ?

Cheers,

Clement.

**Comment by AnastasiiaSergienko** [comment] 2021-07-13 13:25
The special characters shouldn't be a problem, a password with an exclamation mark is parsed correctly, I've tested it just in case. :)

**Comment by AnastasiiaSergienko** [comment] 2021-07-14 12:05
@clementlefevre I'm closing the ticket for now. If you have additional questions, please feel free to re-open it. :)

**Closed by AnastasiiaSergienko** 2021-07-14 12:05 UTC
Labels: bug, source:external
